### ISSUE TITLE
Path parameters in "Path Item Object" not correctly validated.

### ISSUE THREAD

**Issue by fabiohecht** [openapi4j/openapi4j#128]
**Describe the bug**
Path parameters in "Path Item Object" not correctly validated.

**To Reproduce**
I tested a schema like the one below, which I believe is a valid one, but the library validation complains about path parameter 'pathParam' in path '/path/{pathParam}' being expected but undefined (code: 124)

```
(...)
/path/{pathParam}
  parameters:
    - name: pathParam
      in: path
      required: true
      description: A path parameter
      schema:
        type: string
  get:
(...)
```

**Expected behavior**
Expected that path parameters can be set in "Path Item Object" and optionally overridden in "Operation Object".
